DROP TABLE IF EXISTS zadania;

CREATE TABLE zadania (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    czas TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    zadanie TEXT NOT NULL,
    priorytet TEXT NOT NULL,
    uname TEXT NOT NULL
);

DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uname TEXT NOT NULL
);